In [1]:
from asm_2o import Asm2o

In [2]:
env = Asm2o()

In [3]:
env.reset()

(array([-0.94812864, -0.18197277], dtype=float32), {})

In [21]:
env.step([-1])[0]

array([-0.95703554,  0.7007429 ], dtype=float32)

In [45]:
import numpy as np
np.max(env.parameters['wt'])

0.9701466

In [42]:
env.parameters['wt']

array([0.00867406, 0.05012764, 0.12382168, 0.2176034 , 0.3191206 ,
       0.4192168 , 0.5122158 , 0.5952108 , 0.667202  , 0.7283712 ,
       0.7795541 , 0.8218887 , 0.856597  , 0.8848603 , 0.9077545 ,
       0.92622364, 0.9410753 , 0.952988  , 0.9625244 , 0.9701466 ],
      dtype=float32)

In [1]:
from msy import Msy
from cautionary_rule import CautionaryRule
from const_esc import ConstEsc

In [17]:
m = Msy(0.5)
cr = CautionaryRule(0, 1, 1)
ce = ConstEsc(0.1)

In [18]:
import numpy as np
state = np.float32([-0.4, 0.])
m.state_to_pop(state)

array([0.3, 0.5], dtype=float32)

In [19]:
f"{m.predict(state)}, {cr.predict(state)}, {ce.predict(state)}"

'[0.], [-0.39999998], [0.33333337]'

In [20]:
f"{m.predict_effort(state)}, {cr.predict_effort(state)}, {ce.predict_effort(state)}"

'[0.5], [0.3], [0.6666667]'